[workspace]

members = [
    "backend",
    "frontend",

    #Internal
    "common"
]

default-members = [
  "backend",
]

[profile.release]
lto = true
debug = false
debug-assertions = false
codegen-units = 1
panic = "abort"
