[build]
target = "./crates/frontend/index.html"
dist = "./static"
release = false
public_url = "/"

[watch]
watch = [
    "./crates/frontend/index.html",
    "./crates/frontend/src",
    "./crates/frontend/styles",
    "./assets"
]

[[proxy]]
backend = "http://localhost:5550"
rewrite = "/api"

[clean]
dist = "./static"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i ./crates/frontend/styles/tailwind.css --minify -c ./crates/frontend/styles/tailwind.config.js -o ./crates/frontend/styles/tailwind.min.css"]
