jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run: cargo version
      - run: rustup toolchain install nightly
      - run: cargo build
      - run: cargo clippy --fix --allow-dirty --allow-staged
      - run: cargo test
      - run: mkdir test-results
      - store_test_results:
          path: test-results
