version: 2.1

executors:
  default:
    docker:
      - image: circleci/rust:latest

commands:
  setup-sccache:
    steps:
      - run:
          name: Install sccache
          command: |
            cargo install sccache
            # This configures Rust to use sccache.
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            # This is the maximum space sccache cache will use on disk.
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
            sccache --version
  restore-sccache-cache:
    steps:
      - restore_cache:
          name: Restore sccache cache
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save-sccache-cache:
    steps:
      - save_cache:
          name: Save sccache cache
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"  
jobs:
  rust_toolchain_install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v0-{{ checksum "rust-toolchain" }}
      - run: rustup install nightly
      - persist_to_workspace:
          root: ~/
          paths:
            - gpuci
      - save_cache:
          key: cargo-v0-{{ checksum "rust-toolchain" }}
          paths:
            - "~/.cargo"
            - "~/.rustup"

  rust-tests:
    executor: default
    steps:
      - checkout
      - rust-toolchain-install
      - setup-sccache
      - restore-sccache-cache
      - run: mkdir test-results
      - run: cargo build
      - run: cargo clippy --fix --allow-dirty --allow-staged
      - run: cargo test
      - save-sccache-cache
      - store_test_results:
          path: test-results
