jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo version
      - run: rustup toolchain install nightly-2022-06-30
      - run: cargo clippy --fix --allow-dirty --allow-staged
      - run: cargo test
      - store_test_results:
          path: test-results
