[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "frontend"
path = "src/bin/main.rs"

[dependencies]
common = { path = "../common" }

yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
serde = { version = "1.0", features = ["derive"] }
derive-getters = "0.2"
lazy_static = "1.4"
gloo-net = "0.2"
