[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "backend"
path = "src/bin/main.rs"

[dependencies]
color-eyre = "0.6"
tracing = "0.1"
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }