[default]
log_level = "info"
is_stdout_emitted = true
is_file_emitted = true
is_wasm_console_emitted = true
logs_directory = "./logs"

[production]
log_level = "warn"
is_stdout_emitted = false
is_file_emitted = true
is_wasm_console_emitted = false
logs_directory = "./logs"
